// Initial Mock Dataset for Editorial Operations Workspace

export const INITIAL_DEPARTMENTS = [
  {
    id: 'DEP-101',
    name: 'Engineering',
    code: 'ENG',
    leadName: 'Amit Joshi',
    description: 'Core product development, infrastructure, and technical operations.',
    budget: '₹48,000,000',
    location: 'Building A - Floor 4',
  },
  {
    id: 'DEP-102',
    name: 'Human Resources',
    code: 'HR',
    leadName: 'Priya Patil',
    description: 'Talent acquisition, organizational culture, compliance, and employee success.',
    budget: '₹14,500,000',
    location: 'Building B - Floor 2',
  },
  {
    id: 'DEP-103',
    name: 'Finance & Accounts',
    code: 'FIN',
    leadName: 'Neha Deshmukh',
    description: 'Financial planning, payroll management, auditing, and corporate treasury.',
    budget: '₹22,000,000',
    location: 'Building A - Floor 5',
  },
  {
    id: 'DEP-104',
    name: 'Operations & Logistics',
    code: 'OPS',
    leadName: 'Rahul Sharma',
    description: 'Day-to-day workplace operations, supply chain, and facilities management.',
    budget: '₹31,000,000',
    location: 'Building B - Ground Floor',
  },
  {
    id: 'DEP-105',
    name: 'Marketing & Brand',
    code: 'MKT',
    leadName: 'Sneha Kulkarni',
    description: 'Growth marketing, brand communications, product PR, and design strategy.',
    budget: '₹19,500,000',
    location: 'Building A - Floor 3',
  },
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'EMP-1001',
    employee_code: 'EMP-1001',
    first_name: 'Rahul',
    last_name: 'Sharma',
    email: 'rahul.sharma@ops.co',
    phone: '+91 98201 44321',
    department: 'Operations & Logistics',
    designation: 'VP of Operations',
    date_of_joining: '2019-03-15',
    salary: '₹2,400,000',
    status: 'ACTIVE',
    avatar: 'RS',
  },
  {
    id: 'EMP-1002',
    employee_code: 'EMP-1002',
    first_name: 'Priya',
    last_name: 'Patil',
    email: 'priya.patil@ops.co',
    phone: '+91 98192 11045',
    department: 'Human Resources',
    designation: 'Head of People Operations',
    date_of_joining: '2020-01-10',
    salary: '₹1,950,000',
    status: 'ACTIVE',
    avatar: 'PP',
  },
  {
    id: 'EMP-1003',
    employee_code: 'EMP-1003',
    first_name: 'Amit',
    last_name: 'Joshi',
    email: 'amit.joshi@ops.co',
    phone: '+91 99304 88120',
    department: 'Engineering',
    designation: 'Principal Architect',
    date_of_joining: '2018-08-01',
    salary: '₹2,800,000',
    status: 'ACTIVE',
    avatar: 'AJ',
  },
  {
    id: 'EMP-1004',
    employee_code: 'EMP-1004',
    first_name: 'Sneha',
    last_name: 'Kulkarni',
    email: 'sneha.kulkarni@ops.co',
    phone: '+91 97690 33412',
    department: 'Marketing & Brand',
    designation: 'Creative Director',
    date_of_joining: '2021-04-18',
    salary: '₹1,700,000',
    status: 'ACTIVE',
    avatar: 'SK',
  },
  {
    id: 'EMP-1005',
    employee_code: 'EMP-1005',
    first_name: 'Neha',
    last_name: 'Deshmukh',
    email: 'neha.deshmukh@ops.co',
    phone: '+91 98210 77654',
    department: 'Finance & Accounts',
    designation: 'Senior Finance Lead',
    date_of_joining: '2020-09-01',
    salary: '₹1,850,000',
    status: 'ACTIVE',
    avatar: 'ND',
  },
  {
    id: 'EMP-1006',
    employee_code: 'EMP-1006',
    first_name: 'Vikrant',
    last_name: 'Mehta',
    email: 'vikrant.mehta@ops.co',
    phone: '+91 98331 22490',
    department: 'Engineering',
    designation: 'Senior Backend Engineer',
    date_of_joining: '2021-11-15',
    salary: '₹1,600,000',
    status: 'ACTIVE',
    avatar: 'VM',
  },
  {
    id: 'EMP-1007',
    employee_code: 'EMP-1007',
    first_name: 'Ananya',
    last_name: 'Iyer',
    email: 'ananya.iyer@ops.co',
    phone: '+91 99200 55189',
    department: 'Engineering',
    designation: 'Frontend Lead',
    date_of_joining: '2022-02-01',
    salary: '₹1,650,000',
    status: 'ACTIVE',
    avatar: 'AI',
  },
  {
    id: 'EMP-1008',
    employee_code: 'EMP-1008',
    first_name: 'Rajesh',
    last_name: 'Nair',
    email: 'rajesh.nair@ops.co',
    phone: '+91 98111 66340',
    department: 'Operations & Logistics',
    designation: 'Facilities Specialist',
    date_of_joining: '2022-06-10',
    salary: '₹950,000',
    status: 'ACTIVE',
    avatar: 'RN',
  },
  {
    id: 'EMP-1009',
    employee_code: 'EMP-1009',
    first_name: 'Kavita',
    last_name: 'Rao',
    email: 'kavita.rao@ops.co',
    phone: '+91 97114 99012',
    department: 'Human Resources',
    designation: 'Recruitment Manager',
    date_of_joining: '2021-08-20',
    salary: '₹1,200,000',
    status: 'ACTIVE',
    avatar: 'KR',
  },
  {
    id: 'EMP-1010',
    employee_code: 'EMP-1010',
    first_name: 'Siddharth',
    last_name: 'Verma',
    email: 'siddharth.verma@ops.co',
    phone: '+91 98205 33118',
    department: 'Engineering',
    designation: 'DevOps Specialist',
    date_of_joining: '2023-01-05',
    salary: '₹1,500,000',
    status: 'ACTIVE',
    avatar: 'SV',
  },
  {
    id: 'EMP-1011',
    employee_code: 'EMP-1011',
    first_name: 'Pooja',
    last_name: 'Hegde',
    email: 'pooja.hegde@ops.co',
    phone: '+91 98300 44102',
    department: 'Marketing & Brand',
    designation: 'Content Strategist',
    date_of_joining: '2023-03-12',
    salary: '₹1,100,000',
    status: 'ACTIVE',
    avatar: 'PH',
  },
  {
    id: 'EMP-1012',
    employee_code: 'EMP-1012',
    first_name: 'Aditya',
    last_name: 'Chavan',
    email: 'aditya.chavan@ops.co',
    phone: '+91 99401 77334',
    department: 'Finance & Accounts',
    designation: 'Payroll Analyst',
    date_of_joining: '2022-10-01',
    salary: '₹1,050,000',
    status: 'ACTIVE',
    avatar: 'AC',
  },
  {
    id: 'EMP-1013',
    employee_code: 'EMP-1013',
    first_name: 'Tanvi',
    last_name: 'Shah',
    email: 'tanvi.shah@ops.co',
    phone: '+91 98209 88123',
    department: 'Engineering',
    designation: 'QA Automation Engineer',
    date_of_joining: '2023-05-18',
    salary: '₹1,250,000',
    status: 'ACTIVE',
    avatar: 'TS',
  },
  {
    id: 'EMP-1014',
    employee_code: 'EMP-1014',
    first_name: 'Karan',
    last_name: 'Malhotra',
    email: 'karan.malhotra@ops.co',
    phone: '+91 98104 22091',
    department: 'Operations & Logistics',
    designation: 'Procurement Specialist',
    date_of_joining: '2021-03-22',
    salary: '₹1,150,000',
    status: 'ACTIVE',
    avatar: 'KM',
  },
  {
    id: 'EMP-1015',
    employee_code: 'EMP-1015',
    first_name: 'Deepika',
    last_name: 'Padukone',
    email: 'deepika.p@ops.co',
    phone: '+91 97691 00214',
    department: 'Marketing & Brand',
    designation: 'Brand Communications Associate',
    date_of_joining: '2023-07-01',
    salary: '₹980,000',
    status: 'ACTIVE',
    avatar: 'DP',
  },
  {
    id: 'EMP-1016',
    employee_code: 'EMP-1016',
    first_name: 'Rohan',
    last_name: 'Gupta',
    email: 'rohan.gupta@ops.co',
    phone: '+91 99201 44510',
    department: 'Engineering',
    designation: 'Junior Fullstack Developer',
    date_of_joining: '2024-01-15',
    salary: '₹900,000',
    status: 'ACTIVE',
    avatar: 'RG',
  },
  {
    id: 'EMP-1017',
    employee_code: 'EMP-1017',
    first_name: 'Gaurav',
    last_name: 'Tiwari',
    email: 'gaurav.tiwari@ops.co',
    phone: '+91 98199 00812',
    department: 'Operations & Logistics',
    designation: 'Logistics Supervisor',
    date_of_joining: '2020-05-10',
    salary: '₹1,300,000',
    status: 'ON_LEAVE',
    avatar: 'GT',
  },
  {
    id: 'EMP-1018',
    employee_code: 'EMP-1018',
    first_name: 'Manish',
    last_name: 'Pandey',
    email: 'manish.pandey@ops.co',
    phone: '+91 98202 77114',
    department: 'Finance & Accounts',
    designation: 'Tax & Compliance Specialist',
    date_of_joining: '2019-11-01',
    salary: '₹1,400,000',
    status: 'ACTIVE',
    avatar: 'MP',
  },
];

export const INITIAL_ATTENDANCE = [
  { id: 'ATT-001', employee_id: 'EMP-1001', employee_name: 'Rahul Sharma', department: 'Operations & Logistics', date: '2026-09-29', check_in: '08:52 AM', check_out: '06:15 PM', status: 'PRESENT', hours: '9.3 hrs' },
  { id: 'ATT-002', employee_id: 'EMP-1002', employee_name: 'Priya Patil', department: 'Human Resources', date: '2026-09-29', check_in: '09:05 AM', check_out: '05:45 PM', status: 'PRESENT', hours: '8.6 hrs' },
  { id: 'ATT-003', employee_id: 'EMP-1003', employee_name: 'Amit Joshi', department: 'Engineering', date: '2026-09-29', check_in: '09:14 AM', check_out: '07:20 PM', status: 'PRESENT', hours: '10.1 hrs' },
  { id: 'ATT-004', employee_id: 'EMP-1004', employee_name: 'Sneha Kulkarni', department: 'Marketing & Brand', date: '2026-09-29', check_in: '09:30 AM', check_out: '06:00 PM', status: 'PRESENT', hours: '8.5 hrs' },
  { id: 'ATT-005', employee_id: 'EMP-1005', employee_name: 'Neha Deshmukh', department: 'Finance & Accounts', date: '2026-09-29', check_in: '08:58 AM', check_out: '05:50 PM', status: 'PRESENT', hours: '8.8 hrs' },
  { id: 'ATT-006', employee_id: 'EMP-1006', employee_name: 'Vikrant Mehta', department: 'Engineering', date: '2026-09-29', check_in: '09:45 AM', check_out: '06:30 PM', status: 'PRESENT', hours: '8.7 hrs' },
  { id: 'ATT-007', employee_id: 'EMP-1007', employee_name: 'Ananya Iyer', department: 'Engineering', date: '2026-09-29', check_in: '09:10 AM', check_out: '06:10 PM', status: 'PRESENT', hours: '9.0 hrs' },
  { id: 'ATT-008', employee_id: 'EMP-1008', employee_name: 'Rajesh Nair', department: 'Operations & Logistics', date: '2026-09-29', check_in: '08:30 AM', check_out: '05:00 PM', status: 'PRESENT', hours: '8.5 hrs' },
  { id: 'ATT-009', employee_id: 'EMP-1009', employee_name: 'Kavita Rao', department: 'Human Resources', date: '2026-09-29', check_in: '10:00 AM', check_out: '02:30 PM', status: 'HALF_DAY', hours: '4.5 hrs' },
  { id: 'ATT-010', employee_id: 'EMP-1010', employee_name: 'Siddharth Verma', department: 'Engineering', date: '2026-09-29', check_in: '09:20 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
  { id: 'ATT-011', employee_id: 'EMP-1011', employee_name: 'Pooja Hegde', department: 'Marketing & Brand', date: '2026-09-29', check_in: '--', check_out: '--', status: 'ABSENT', hours: '0 hrs' },
  { id: 'ATT-012', employee_id: 'EMP-1012', employee_name: 'Aditya Chavan', department: 'Finance & Accounts', date: '2026-09-29', check_in: '09:02 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
  { id: 'ATT-013', employee_id: 'EMP-1013', employee_name: 'Tanvi Shah', department: 'Engineering', date: '2026-09-29', check_in: '09:15 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
  { id: 'ATT-014', employee_id: 'EMP-1014', employee_name: 'Karan Malhotra', department: 'Operations & Logistics', date: '2026-09-29', check_in: '08:45 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
  { id: 'ATT-015', employee_id: 'EMP-1015', employee_name: 'Deepika Padukone', department: 'Marketing & Brand', date: '2026-09-29', check_in: '09:35 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
  { id: 'ATT-016', employee_id: 'EMP-1016', employee_name: 'Rohan Gupta', department: 'Engineering', date: '2026-09-29', check_in: '09:00 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
  { id: 'ATT-017', employee_id: 'EMP-1017', employee_name: 'Gaurav Tiwari', department: 'Operations & Logistics', date: '2026-09-29', check_in: '--', check_out: '--', status: 'ABSENT', hours: '0 hrs' },
  { id: 'ATT-018', employee_id: 'EMP-1018', employee_name: 'Manish Pandey', department: 'Finance & Accounts', date: '2026-09-29', check_in: '08:50 AM', check_out: '--', status: 'PRESENT', hours: 'In Progress' },
];

export const INITIAL_LEAVES = [
  {
    id: 'LV-901',
    employee_id: 'EMP-1017',
    employee_name: 'Gaurav Tiwari',
    employee_code: 'EMP-1017',
    department: 'Operations & Logistics',
    designation: 'Logistics Supervisor',
    leave_type: 'Casual Leave',
    start_date: '2026-09-28',
    end_date: '2026-10-02',
    days_count: 5,
    reason: 'Family event and personal travel to Kanpur.',
    status: 'PENDING',
    applied_on: '2026-09-25',
  },
  {
    id: 'LV-902',
    employee_id: 'EMP-1011',
    employee_name: 'Pooja Hegde',
    employee_code: 'EMP-1011',
    department: 'Marketing & Brand',
    designation: 'Content Strategist',
    leave_type: 'Sick Leave',
    start_date: '2026-09-29',
    end_date: '2026-09-30',
    days_count: 2,
    reason: 'Acute seasonal flu and doctor advised bed rest.',
    status: 'PENDING',
    applied_on: '2026-09-28',
  },
  {
    id: 'LV-903',
    employee_id: 'EMP-1006',
    employee_name: 'Vikrant Mehta',
    employee_code: 'EMP-1006',
    department: 'Engineering',
    designation: 'Senior Backend Engineer',
    leave_type: 'Earned Leave',
    start_date: '2026-10-10',
    end_date: '2026-10-15',
    days_count: 6,
    reason: 'Attending technical conference in Bengaluru & personal vacation.',
    status: 'APPROVED',
    applied_on: '2026-09-20',
  },
  {
    id: 'LV-904',
    employee_id: 'EMP-1009',
    employee_name: 'Kavita Rao',
    employee_code: 'EMP-1009',
    department: 'Human Resources',
    designation: 'Recruitment Manager',
    leave_type: 'Half Day',
    start_date: '2026-09-29',
    end_date: '2026-09-29',
    days_count: 0.5,
    reason: 'Scheduled medical appointment in the afternoon.',
    status: 'APPROVED',
    applied_on: '2026-09-27',
  },
  {
    id: 'LV-905',
    employee_id: 'EMP-1016',
    employee_name: 'Rohan Gupta',
    employee_code: 'EMP-1016',
    department: 'Engineering',
    designation: 'Junior Fullstack Developer',
    leave_type: 'Casual Leave',
    start_date: '2026-09-15',
    end_date: '2026-09-16',
    days_count: 2,
    reason: 'Urgent home maintenance work.',
    status: 'REJECTED',
    applied_on: '2026-09-14',
    rejection_reason: 'Project release deployment scheduled on requested dates.',
  },
];

export const RECENT_ACTIVITY_LOGS = [
  { id: 'ACT-001', time: '10:00 AM', title: 'Half Day Logged', desc: 'Kavita Rao marked half-day leave for afternoon doctor appointment.', type: 'ATTENDANCE' },
  { id: 'ACT-002', time: '09:45 AM', title: 'Check-in Recorded', desc: 'Vikrant Mehta checked in via terminal B4.', type: 'CHECKIN' },
  { id: 'ACT-003', time: '09:14 AM', title: 'Check-in Recorded', desc: 'Amit Joshi checked in via terminal A1.', type: 'CHECKIN' },
  { id: 'ACT-004', time: '09:00 AM', title: 'Leave Application', desc: 'Pooja Hegde requested 2 days Sick Leave.', type: 'LEAVE' },
  { id: 'ACT-005', time: '08:52 AM', title: 'Check-in Recorded', desc: 'Rahul Sharma checked in via terminal A2.', type: 'CHECKIN' },
];
